### ISSUE TITLE
You can spam /refferals thanks

### ISSUE THREAD

**Issue by Shybella** [L-E-iT/Referrals#4]
It seems you can spam /refferals thanks and be rewarded everytime.

You should only be allowed to thank once per player and be rewarded once per player.

**Comment by Shybella** [comment]
The referred player should also have to /accept the referrers referral.
 
Other than both of those problems, this is a promising plugin and I would love to help anyway I can.

Thank you.

**Comment by shinzoop1** [comment]
Normal players can repeatedly do this, but an OP cannot as it actually tracks the player who is linked as the referrer.

**Comment by L-E-iT** [comment]
Interesting. I'll take a look at this soon and try to implement a fix.

Ill try to get this replicated on my end and fix it as soon as I am able to.

**Comment by L-E-iT** [comment]
Found the issue an fixed it here: https://github.com/L-E-iT/Referrals/commit/68a792e90f702f36f4335bb671eacf153c83b69d

This doesn't add the acceptance of a referral, but I would rather have that tracked in another issue for future enhancement.

**Comment by Shybella** [comment]
Thank you I will be testing this out today!
