### ISSUE TITLE
Permission to publish derivative on Ore

### ISSUE THREAD

**Issue by Robit** [L-E-iT/Referrals#7]
Hey there,

I'd like to fork this plugin and add more features and customization to it for my own use as allowed by the MIT license. If I do so, is it all right with you if I publish it on Ore? I'd leave a link to your plugin at the top of the page and respect the stipulations of the license. 

Thank you, 
rm2023

**Comment by L-E-iT** [comment]
Sure thing!  I'd love to see where you take the plugin :)

Feel free to give the plugin a new name if you do publish to Ore, I'd like to keep my own page of the plugin should I ever return to continue development on it. Happy to provide a base for you to work with though!
